### ISSUE TITLE
[Feature Improvement] Add Better Respawn Modes

### ISSUE THREAD

**Issue by dgibso29** [CombinedArmsGaming/CAFE3#29]
add better respawn modes because CO waves kinda suck
- [ ] 🔴 make swappable respawn mode system
- [ ] 🔴 prototype mode: instant respawn
- [ ] 🔴 mp test
- [ ] 🔴 CO ticket respawn
- [ ] 🔴 auto ticket respawn
- [ ] 🔴 auto wave respawn (n-player)
- [ ] 🔴 auto wave respawn 
- [ ] 🔴 mp test

**Comment by Joecuronium** [comment]
Additionally: rework the whole spectate/respawn system, since it seems to be breaking a lot.

**Comment by Joecuronium** [comment]
putting note here: Possibly transition to event handler based respawn? I guess the whole "replace player unit with temp AI" messes with some stuff
